---
- name: Apt update
  apt:
    name:
      - ca-certificates
      - curl
      - python3-pip

- name: Add apt key
  get_url:
    dest: /etc/apt/trusted.gpg.d/docker.asc
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Get DEB arch
  shell: dpkg --print-architecture
  register: deb_arch

- name: Add docker repo
  apt_repository:
    filename: docker
    repo: "deb [arch={{ deb_arch.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Install Docker SDK for python
  pip:
    name:
      - docker
      - docker-compose
